<?php

/**
 * {@inheritdoc}
 */
function cohesion_layout_builder_theme() {
  return [
    'cohesion_layout_builder' => [
      'variables' => ['content' => NULL],
    ],
  ];
}

/**
 * Implement hook_theme_suggesions_alter().
 */
function cohesion_layout_builder_theme_suggestions_cohesion_layout_builder_alter(array &$suggestions, array &$variables) {

  $parameters = \Drupal::routeMatch()->getParameters(); // Detect what kind of entity we're looking at.

  // Loaded admin/structure/types/manage/{bundle}/display-layout/default
  if ($parameters->get('view_mode_name')) {
    $entity_type_id = $parameters->get('entity_type_id');

    $entity = \Drupal::entityTypeManager()->getStorage($entity_type_id)->create([
        'bundle_key' => $parameters->get('bundle_key'),
        'type' => $parameters->get($parameters->get('bundle_key')),
      ]);
  }
  // Loaded {entity}/{entity_id}/layout
  else {
    if ($entity_type_id = $parameters->get('entity_type_id')) {
      $entity = $parameters->get($parameters->get('entity_type_id'));
    }
    else {
      // AJAX move/insert request (this will cover the above block, but that is
      // way faster for it's use case.
      if ($section_storage = $parameters->get('section_storage')) {
        $storage_id = explode('.', $section_storage->getStorageId());
        $entity_type_id = $storage_id[0];

        // Editing default layout.
        if (isset($storage_id[2]) && $storage_id[2] == 'default') {
          $entity = \Drupal::entityTypeManager()->getStorage($entity_type_id)->create([
              'bundle_key' => $entity_type_id . '_type',
              'type' => $entity_id = $storage_id[1],
            ]);
        }
        // Existing entity.
        else {
          $entity_id = $storage_id[1];

          // Load the entity.
          try {
            /** @var Drupal\Core\Entity\ContentEntityInterface $entity */
            $entity = \Drupal::entityTypeManager()->getStorage($entity_type_id)->load($entity_id);
          } catch (\Exception $e) {
            return;
          }
        }
      }
    }
  }

  // Set the entity in the variables so the entity preprocessor has access to it.
  $variables['elements']['#' . $entity_type_id] = $entity;

  // Give the content template suggestion for this entity.
  cohesion_templates_suggestions($suggestions, $entity, 'full', $entity_type_id);
}

