<?php 
/** 
 * @file 
 * file acquia_support_reports.module
 *
 */ 

/** 
 * Implementation of hook_init().
 */
function acquia_support_reports_init() {
  drupal_add_css(drupal_get_path('module', 'acquia_support_reports'). '/acquia_support_reports.css');
  drupal_add_js(drupal_get_path('module', 'acquia_support_reports'). '/acquia_support_reports.js');
}
/** 
 * Implementation of hook_menu(). 
 */ 
function acquia_support_reports_menu() {
  $items['reports/summary'] = array( 
    'title' => 'Reports Summary', 
    'description' => 'Reports Summary',
    'page callback' => 'acquia_support_reports_summary', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );  
 
  return $items; 
}

/**
 * Page callback for reports summary page. 
 */
function acquia_support_reports_summary() {
  drupal_set_title('Reports Summary');
  // customers, installs, and sites by status
  $header = array('Status', 'Total');
  //$statuses = db_query("SELECT field_status_value FROM {field_data_field_status}
  $status[] = array('Not Secure', '3');
  $status[] = array('Revoked', '0');
  $status[] = array('Not Supported', '0');
  $status[] = array('Not Current', '1');
  $status[] = array('Current', '1');
  $status[] = array('Not Checked', '0');
  $status[] = array('Unknown', '1');
  $status[] = array('Not Fetched', '0');
  $status[] = array('Fetch Pending', '0');

  $output = acquia_support_reports_summary_status_chart();
  $output .= theme('table', array('header' => $header, 'rows' => $status));

  return $output;
}

/**
 * Implementation of hook_block().
 */
function acquia_support_reports_block_info() {
}

function acquia_support_reports_block_view($delta = '') {
}

function acquia_support_reports_summary_status_chart() {
  $chart = array(
    '#chart_id' => 'summary',
    '#title' => t('Status Summary'),
    '#type' => CHART_TYPE_PIE,
    '#size' => array('500px', '500px'),
    '#legends' => array('Not Secure', 'Not Current', 'Current', 'Unknown'),
  );
  
  $chart['#data']['Not Secure'] = 3;
  //$chart['#data']['Revoked'] = 0;
  //$chart['#data']['Not Supported'] = 0;
  $chart['#data']['Not Current'] = 1;
  $chart['#data']['Current'] = 1;
  $chart['#data']['Unknown'] = 1;

  return theme('chart', array('chart' => $chart));
}

