<?php

/**
 * @file
 * An implementation of node revision workflow for Drupal based on the
 * State Machine system and State Flow module.
 */


 /**
 * Implements hook_state_flow_plugins().
 */
function rastates_workflow_state_flow_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'rastates') . '/plugins';
  $info['rastates_workflow'] = array(
    'handler' => array(
      'parent' => 'state_flow',
      'class' => 'RAWorkflow',
      'file' => 'rastates_workflow.inc',
      'path' => $path,
    ),
  );
  return $info;
}
function rastates_state_flow_machine_type_alter(&$machine_type, $node) {
  $machine_type = "article";
}
