<?php
function racustom_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ra_su_preferences_node_form') {
    $form['raprefs_info'] = array(
      '#markup' => t('This form is v1 of a template to create client-facing RA Update preferences.  Eventually, clients will fill this in with three pre-options:  <ul><li>Full (we automatically do everything through deployment on Stage),</li><li>Update Only (we provide an updated branch),</li><li>Inform Only (we just inform them that their site has pending updates).</li></ul>  Clients will also have the option to customize as well, selecting the preferred environment, etc.  See <a target="_blank" href="https://mgmacquia1.mybalsamiq.com/projects/clientraoptions/grid">a quick wireframe.</a>'));
  }
  if ($form_id == 'security_updates_node_form') {
    $form['field_su_module_updates']['und']['#description']
        = 'somthing or other';
  }
}

