<?php 
/** 
 * @file 
 * file acquia_support_dashboard.module
 *
 */ 

/** 
 * Implementation of hook_init().
 */
function acquia_support_dashboard_init() {
  drupal_add_css(drupal_get_path('module', 'acquia_support_dashboard'). '/acquia_support_dashboard.css');
  drupal_add_js(drupal_get_path('module', 'acquia_support_dashboard'). '/acquia_support_dashboard.js');
}
/** 
 * Implementation of hook_menu(). 
 */ 
function acquia_support_dashboard_menu() {
  $items['dashboard'] = array( 
    'title' => 'My Dashboard', 
    'description' => 'Dashboard page for RA dashboard',
    'page callback' => 'acquia_support_dashboard_overview', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );  
 
  return $items; 
}

/**
 * Page callback for dashboard page.
 */
function acquia_support_dashboard_overview() {
  drupal_set_title('My Dashboard');
  return '';
}

/**
 * Implementation of hook_block().
 */
function acquia_support_dashboard_block_info() {
  $blocks = array();

  $blocks['dashboard_stats_overview'] = array(
    'info' => t('RA Dashboard Stats Overview'),
    //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['site_information_links'] = array(
    'info' => t('Individual Site Information Links'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['tasks_open'] = array(
    'info' => t('Unassigned Tasks'),
    //'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

function acquia_support_dashboard_block_view($delta = '') {
  $blocks = array();

  switch ($delta) {
    case 'dashboard_stats_overview':
      $block['subject'] = t('Overview');
      $block['content'] = acquia_support_dashboard_stats_overview();
      break;
    case 'site_information_links':
      // Primary site links
      $links = array();
      $links[] = l('Overview', 'node/'. arg(1)); 
      $links[] = l('Credentials', 'site-credentials/'. arg(1));
      $links[] = l('Site Profile', 'site-profile/'. arg(1));
      //$links[] = l('Server Info', 'server-info/'. arg(1));
      //$links[] = l('All Tasks', 'site-tasks/'. arg(1));
      $output = theme('item_list', array('items' => $links, 'attributes' => array('class' => 'site-information')));

      // Secondary site links
      $secondary = array();
      $secondary[] = l('track', '');
      // TODO: Add prepopulate
      $secondary[] = l('create task', 'node/add/task');
      $secondary[] = l('add credentials', 'node/add/credentials');
      $output .= theme('item_list', array('items' => $secondary, 'attributes' => array('class' => 'site-secondary')));

      $block['content'] = $output;
      break;
    case 'tasks_open':
      $tasks = db_query("SELECT COUNT(*) FROM {node} LEFT JOIN {flag_content} ON node.nid = flag_content.content_id WHERE node.type = 'task' AND content_id IS NULL")->fetchField();
      $block['subject'] = t('Tasks');
      $block['content'] = l('Unassigned Tasks: '. $tasks, 'tasks'); 
  }
  return $block;
}

function acquia_support_dashboard_stats_overview() {
  global $user;
    
  $subscriptions_overall = db_query("SELECT COUNT(*) FROM {node} WHERE type = 'account'")->fetchField(); 
  $tasks_overall = db_query("SELECT COUNT(*) FROM {node} LEFT JOIN {flag_content} ON node.nid = flag_content.content_id WHERE node.type = 'task' AND content_id IS NULL")->fetchField(); 
  $subscriptions_new = db_query("SELECT COUNT(*) FROM {node} WHERE type = 'account' AND created > (UNIX_TIMESTAMP() - 604800)")->fetchField();
  $tasks_new = db_query("SELECT COUNT(*) FROM {node} WHERE type = 'task' AND created > (UNIX_TIMESTAMP() - 604800)")->fetchField();
  //$tasks_complete = 15;
  //'select count(*) from flag_content where fid = 6';
    
  // TODO: Break this down into smaller crud and theme functions
  $overall = array(
    'accounts' => '<div class="overview-label">Subscriptions:</div><div class="overview-content">' . $subscriptions_overall . '</div>',
    'tasks' => '<div class="overview-label">Unassigned Tasks:</div><div class="overview-content">' . $tasks_overall . '</div>',
  );

  $weekly = array(
    'accounts_new' => '<div class="overview-label">New Subscriptions:</div><div class="overview-content">' . $subscriptions_new . '</div>',
    'tasks_new' => '<div class="overview-label">New Tasks:</div><div class="overview-content">' . $tasks_new . '</div>',
    //'tasks_complete' => '<div class="overview-label">Completed Tasks:</div><div class="overview-content">' . $tasks_complete . '</div>',
  );

  $output = theme('item_list', array('items' => $overall, 'title' => 'Overall'));
  $output .= theme('item_list', array('items' => $weekly, 'title' => 'This Week'));

  return $output;
}

function acquia_support_dashboard_nodeapi_insert($node) {
  if ($node->type == 'task') {
  }
}
