<?php
/**
 * Implements hook_page_attachments().
 * Load library if user has permission.
 */
function cohesion_breakpoint_indicator_page_attachments(array &$attachments) {

  $user = \Drupal::currentUser();
  $permission = $user->hasPermission('access cohesion breakpoint indicator');
  $current_theme = \Drupal::service('theme.manager')->getActiveTheme();
  $is_admin = \Drupal::config('system.theme')->get('admin') == $current_theme->getName();

  // check if the user has permission & not on an admin url.
  if ($permission && !$is_admin) {
    $attachments['#attached']['library'][] = 'cohesion_breakpoint_indicator/cohesion-breakpoint-indicator';
  }
}